export const ADD_NOTE = 'add_note'
export const REMOVE_NOTE = 'remove_note'
export const UPDATE_COLOR = 'update_color'
export const UPDATE_POSITION = 'update_position'
export const UPDATE_CONTENT = 'update_content'